version: "3.7"

services:
  api:
    image: "api:local-dev"
    build:
      context: ./
    volumes:
      - "./:/opt/mockDraft/api"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2-bionic
    restart: always
    ports:  
      - "27017:27017"
    volumes:
      - "/home/ian/Documents/projects/storage/mockDraft:/data/db"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081