#!/bin/bash

# This file uses the pullPff.js script to create the stateful
# players.js file in this project to use as seeding data for
# the mock draft simulator.

PLAYERS_JS="./scripts/seed/players.js"

echo "// THIS FILE IS AUTOGENERATED; YOU WILL NEED TO MANUALLY UPDATE THE SCORES FOR EACH PLAYER." > ${PLAYERS_JS}
echo "const players = " >> ${PLAYERS_JS}
node ./scripts/data_retrieval/pullPff.js >> ${PLAYERS_JS}