const draftOrder = [
  {
    year: 2021,
    r1: [
      "Jaguars",
      "Jets",
      "49ers",
      "Falcons",
      "Bengals",
      "Dolphins",
      "Lions",
      "Panthers",
      "Broncos",
      "Cowboys",
      "Giants",
      "Eagles",
      "Chargers",
      "Vikings",
      "Patriots",
      "Cardinals",
      "Raiders",
      "Dolphins",
      "Football Team",
      "Bears",
      "Colts",
      "Titans",
      "Jets",
      "Steelers",
      "Jaguars",
      "Browns",
      "Ravens",
      "Saints",
      "Packers",
      "Bills",
      "Ravens",
      "Buccaneers"
    ],
    r2: [
      "Jaguars",
      "Jets",
      "Broncos",
      "Dolphins",
      "Eagles",
      "Patriots",
      "Bears",
      "Falcons",
      "Lions",
      "Dolphins",
      "Raiders",
      "Cowboys",
      "Jaguars",
      "Bengals",
      "Chargers",
      "49ers",
      "Cardinals",
      "Giants",
      "Football Team",
      "Browns",
      "Titans",
      "Colts",
      "Steelers",
      "Seahawks",
      "Rams",
      "Chiefs",
      "Panthers",
      "Saints",
      "Bills",
      "Packers",
      "Chiefs",
      "Buccaneers"
    ],
    r3: [],
    r4: [],
    r5: [],
    r6: [],
    r7: []
  }
]

module.exports = draftOrder;