// THIS FILE IS AUTOGENERATED; YOU WILL NEED TO MANUALLY UPDATE THE SCORES FOR EACH PLAYER.
const players = 
[
  {
    firstName: 'Spencer',
    lastName: 'Rattler',
    program: 'Oklahoma Sooners',
    position: 'QB',
    rank: 1,
    score: 0
  },
  {
    firstName: 'Derek',
    lastName: 'Stingley Jr.',
    program: 'LSU Tigers',
    position: 'CB',
    rank: 2,
    score: 0
  },
  {
    firstName: 'Kayvon',
    lastName: 'Thibodeaux',
    program: 'Oregon Ducks',
    position: 'ED',
    rank: 3,
    score: 0
  },
  {
    firstName: 'Kyle',
    lastName: 'Hamilton',
    program: 'Notre Dame Fighting Irish',
    position: 'S',
    rank: 4,
    score: 0
  },
  {
    firstName: 'DeMarvin',
    lastName: 'Leal',
    program: 'Texas A&M Aggies',
    position: 'ED',
    rank: 5,
    score: 0
  },
  {
    firstName: 'Evan',
    lastName: 'Neal',
    program: 'Alabama Crimson Tide',
    position: 'T',
    rank: 6,
    score: 0
  },
  {
    firstName: 'Sam',
    lastName: 'Howell',
    program: 'North Carolina Tar Heels',
    position: 'QB',
    rank: 7,
    score: 0
  },
  {
    firstName: 'Garrett',
    lastName: 'Wilson',
    program: 'Ohio State Buckeyes',
    position: 'WR',
    rank: 8,
    score: 0
  },
  {
    firstName: 'Kaiir',
    lastName: 'Elam',
    program: 'Florida Gators',
    position: 'CB',
    rank: 9,
    score: 0
  },
  {
    firstName: 'Kingsley',
    lastName: 'Enagbare',
    program: 'South Carolina Gamecocks',
    position: 'ED',
    rank: 10,
    score: 0
  },
  {
    firstName: 'Tyler',
    lastName: 'Linderbaum',
    program: 'Iowa Hawkeyes',
    position: 'C',
    rank: 11,
    score: 0
  },
  {
    firstName: 'Trent',
    lastName: 'McDuffie',
    program: 'Washington Huskies',
    position: 'CB',
    rank: 12,
    score: 0
  },
  {
    firstName: 'Adam',
    lastName: 'Anderson',
    program: 'Georgia Bulldogs',
    position: 'ED',
    rank: 13,
    score: 0
  },
  {
    firstName: 'Jaxson',
    lastName: 'Kirkland',
    program: 'Washington Huskies',
    position: 'T',
    rank: 14,
    score: 0
  },
  {
    firstName: 'Chris',
    lastName: 'Olave',
    program: 'Ohio State Buckeyes',
    position: 'WR',
    rank: 15,
    score: 0
  },
  {
    firstName: 'Kedon',
    lastName: 'Slovis',
    program: 'USC Trojans',
    position: 'QB',
    rank: 16,
    score: 0
  },
  {
    firstName: 'Nik',
    lastName: 'Bonitto',
    program: 'Oklahoma Sooners',
    position: 'ED',
    rank: 17,
    score: 0
  },
  {
    firstName: 'Ahmad',
    lastName: 'Gardner',
    program: 'Cincinnati Bearcats',
    position: 'CB',
    rank: 18,
    score: 0
  },
  {
    firstName: 'Treylon',
    lastName: 'Burks',
    program: 'Arkansas Razorbacks',
    position: 'WR',
    rank: 19,
    score: 0
  },
  {
    firstName: 'Zach',
    lastName: 'Harrison',
    program: 'Ohio State Buckeyes',
    position: 'ED',
    rank: 20,
    score: 0
  },
  {
    firstName: 'Noah',
    lastName: 'Daniels',
    program: 'TCU Horned Frogs',
    position: 'CB',
    rank: 21,
    score: 0
  },
  {
    firstName: 'Aidan',
    lastName: 'Hutchinson',
    program: 'Michigan Wolverines',
    position: 'ED',
    rank: 22,
    score: 0
  },
  {
    firstName: 'Romeo',
    lastName: 'Doubs',
    program: 'Nevada Wolf Pack',
    position: 'WR',
    rank: 23,
    score: 0
  },
  {
    firstName: 'John',
    lastName: 'Metchie III',
    program: 'Alabama Crimson Tide',
    position: 'WR',
    rank: 24,
    score: 0
  },
  {
    firstName: 'Breece',
    lastName: 'Hall',
    program: 'Iowa State Cyclones',
    position: 'HB',
    rank: 25,
    score: 0
  },
  {
    firstName: 'Mike',
    lastName: 'Jones Jr.',
    program: 'LSU Tigers',
    position: 'LB',
    rank: 26,
    score: 0
  },
  {
    firstName: 'Jaquan',
    lastName: 'Brisker',
    program: 'Penn State Nittany Lions',
    position: 'S',
    rank: 27,
    score: 0
  },
  {
    firstName: 'Darian',
    lastName: 'Kinnard',
    program: 'Kentucky Wildcats',
    position: 'T',
    rank: 28,
    score: 0
  },
  {
    firstName: 'Thayer',
    lastName: 'Munford',
    program: 'Ohio State Buckeyes',
    position: 'T',
    rank: 29,
    score: 0
  },
  {
    firstName: 'Brenton',
    lastName: 'Cox Jr.',
    program: 'Florida Gators',
    position: 'ED',
    rank: 30,
    score: 0
  },
  {
    firstName: 'Martin',
    lastName: 'Emerson',
    program: 'Mississippi State Bulldogs',
    position: 'CB',
    rank: 31,
    score: 0
  },
  {
    firstName: 'Emory',
    lastName: 'Jones',
    program: 'Florida Gators',
    position: 'QB',
    rank: 32,
    score: 0
  },
  {
    firstName: 'Matt',
    lastName: 'Corral',
    program: 'Mississippi Rebels',
    position: 'QB',
    rank: 33,
    score: 0
  },
  {
    firstName: 'Dominick',
    lastName: 'Blaylock',
    program: 'Georgia Bulldogs',
    position: 'WR',
    rank: 34,
    score: 0
  },
  {
    firstName: 'Phidarian',
    lastName: 'Mathis',
    program: 'Alabama Crimson Tide',
    position: 'DI',
    rank: 35,
    score: 0
  },
  {
    firstName: 'Abraham',
    lastName: 'Lucas',
    program: 'Washington State Cougars',
    position: 'T',
    rank: 36,
    score: 0
  },
  {
    firstName: 'Isaiah',
    lastName: 'Likely',
    program: 'Coastal Carolina Chanticleers',
    position: 'TE',
    rank: 37,
    score: 0
  },
  {
    firstName: 'David',
    lastName: 'Bell',
    program: 'Purdue Boilermakers',
    position: 'WR',
    rank: 38,
    score: 0
  },
  {
    firstName: 'Tvondre',
    lastName: 'Sweat',
    program: 'Texas Longhorns',
    position: 'DI',
    rank: 39,
    score: 0
  },
  {
    firstName: 'Jordan',
    lastName: 'McFadden',
    program: 'Clemson Tigers',
    position: 'T',
    rank: 40,
    score: 0
  },
  {
    firstName: 'Jerrion',
    lastName: 'Ealy',
    program: 'Mississippi Rebels',
    position: 'HB',
    rank: 41,
    score: 0
  },
  {
    firstName: "Tre'Vius",
    lastName: 'Hodges-Tomlinson',
    program: 'TCU Horned Frogs',
    position: 'CB',
    rank: 42,
    score: 0
  },
  {
    firstName: 'Daniel',
    lastName: 'Faalele',
    program: 'Minnesota Golden Gophers',
    position: 'T',
    rank: 43,
    score: 0
  },
  {
    firstName: 'Jahan',
    lastName: 'Dotson',
    program: 'Penn State Nittany Lions',
    position: 'WR',
    rank: 44,
    score: 0
  },
  {
    firstName: 'JT',
    lastName: 'Daniels',
    program: 'Georgia Bulldogs',
    position: 'QB',
    rank: 45,
    score: 0
  },
  {
    firstName: 'Dylan',
    lastName: 'Parham',
    program: 'North Carolina State Wolfpack',
    position: 'TE',
    rank: 46,
    score: 0
  },
  {
    firstName: 'Roger',
    lastName: 'McCreary',
    program: 'Auburn Tigers',
    position: 'CB',
    rank: 47,
    score: 0
  },
  {
    firstName: 'Ventrell',
    lastName: 'Miller',
    program: 'Florida Gators',
    position: 'LB',
    rank: 48,
    score: 0
  },
  {
    firstName: 'Chris',
    lastName: 'Rodriguez Jr.',
    program: 'Kentucky Wildcats',
    position: 'HB',
    rank: 49,
    score: 0
  },
  {
    firstName: 'Tykee',
    lastName: 'Smith',
    program: 'West Virginia Mountaineers',
    position: 'S',
    rank: 50,
    score: 0
  }
]
module.exports = players;
